// Package config handles TOML configuration parsing and validation.
// Config lives at /etc/kagami/kagami.toml by default (overridable via
// --config flag). Defines the top-level config struct with server URL,
// machine secret, and per-tunnel service mappings.
package config

import (
	"errors"
	"fmt"
	"os"
	"time"

	"github.com/BurntSushi/toml"
)

// Default values for optional fields.
const (
	DefaultPingInterval         = "30s"
	DefaultReconnectInterval    = "5s"
	DefaultMaxReconnectInterval = "60s"
	DefaultProxyTimeout         = "25s"
	DefaultProtocol             = "http"
)

// Config is the top-level kagami configuration.
type Config struct {
	Agent  AgentConfig    `toml:"agent"`
	Tunnel []TunnelConfig `toml:"tunnel"`
}

// AgentConfig holds agent-level settings.
type AgentConfig struct {
	// TunnelID is the user-chosen name for this machine's tunnel.
	// Maps to DO name: idFromName(TunnelID).
	// Set during `kagami init`.
	TunnelID string `toml:"tunnel_id"`

	// Secret is the per-machine secret for agent authentication.
	// Generated by the Worker during registration and stored locally.
	// Set during `kagami init`.
	Secret string `toml:"secret"`

	// Server is the Worker base URL to connect to (e.g., "kagami.myworkers.dev").
	// Set during `kagami init`.
	Server string `toml:"server"`

	// PingInterval is the interval between keepalive pings sent to the DO (default: 30s).
	// Parsed as a Go duration string (e.g., "30s", "1m").
	PingInterval string `toml:"ping_interval,omitempty"`

	// ReconnectInterval is the base delay before reconnecting (default: 5s).
	// Parsed as a Go duration string (e.g., "5s", "30s").
	ReconnectInterval string `toml:"reconnect_interval,omitempty"`

	// MaxReconnectInterval is the max backoff delay (default: 60s).
	// Parsed as a Go duration string (e.g., "60s", "5m").
	MaxReconnectInterval string `toml:"max_reconnect_interval,omitempty"`

	// ProxyTimeout is the timeout for forwarding requests to local services (default: 25s).
	// Should be less than the DO-side 30s timeout to allow the agent to respond with an error
	// before the DO gives up. Parsed as a Go duration string (e.g., "25s", "30s").
	ProxyTimeout string `toml:"proxy_timeout,omitempty"`

	// Insecure uses ws:// instead of wss:// for the WebSocket connection.
	// Only for local development (e.g., connecting to wrangler dev).
	Insecure bool `toml:"insecure,omitempty"`
}

// TunnelConfig defines a local service to expose.
type TunnelConfig struct {
	// Name is a human-readable label for this tunnel entry.
	Name string `toml:"name"`

	// LocalAddr is the address of the local service (e.g., "localhost:8080").
	LocalAddr string `toml:"local_addr"`

	// Hostname is the public hostname that routes to this service.
	// Used for hostname-based routing within the DO.
	Hostname string `toml:"hostname,omitempty"`

	// PathPrefix routes requests matching this prefix to this service.
	// Used when multiple services share a single hostname.
	PathPrefix string `toml:"path_prefix,omitempty"`

	// Protocol is the protocol to use when connecting to the local service.
	// One of: "http" (default), "https".
	Protocol string `toml:"protocol,omitempty"`
}

// Load reads a TOML config file, applies defaults, and validates the result.
func Load(path string) (*Config, error) {
	data, err := os.ReadFile(path)
	if err != nil {
		return nil, fmt.Errorf("reading config file: %w", err)
	}

	var cfg Config
	if err := toml.Unmarshal(data, &cfg); err != nil {
		return nil, fmt.Errorf("parsing config file: %w", err)
	}

	applyDefaults(&cfg)

	if err := validate(&cfg); err != nil {
		return nil, err
	}

	return &cfg, nil
}

// applyDefaults sets default values for optional fields that were not specified.
func applyDefaults(cfg *Config) {
	if cfg.Agent.PingInterval == "" {
		cfg.Agent.PingInterval = DefaultPingInterval
	}
	if cfg.Agent.ReconnectInterval == "" {
		cfg.Agent.ReconnectInterval = DefaultReconnectInterval
	}
	if cfg.Agent.MaxReconnectInterval == "" {
		cfg.Agent.MaxReconnectInterval = DefaultMaxReconnectInterval
	}
	if cfg.Agent.ProxyTimeout == "" {
		cfg.Agent.ProxyTimeout = DefaultProxyTimeout
	}
	for i := range cfg.Tunnel {
		if cfg.Tunnel[i].Protocol == "" {
			cfg.Tunnel[i].Protocol = DefaultProtocol
		}
	}
}

// validate checks that all required fields are present and duration fields parse correctly.
func validate(cfg *Config) error {
	// Required agent fields.
	if cfg.Agent.TunnelID == "" {
		return errors.New("config: agent.tunnel_id is required")
	}
	if cfg.Agent.Secret == "" {
		return errors.New("config: agent.secret is required")
	}
	if cfg.Agent.Server == "" {
		return errors.New("config: agent.server is required")
	}

	// At least one tunnel entry.
	if len(cfg.Tunnel) == 0 {
		return errors.New("config: at least one [[tunnel]] entry is required")
	}

	// Validate each tunnel entry.
	for i, t := range cfg.Tunnel {
		label := tunnelLabel(i, t.Name)

		if t.LocalAddr == "" {
			return fmt.Errorf("config: %s: local_addr is required", label)
		}
		if t.Hostname == "" && t.PathPrefix == "" {
			return fmt.Errorf("config: %s: at least one of hostname or path_prefix is required", label)
		}
	}

	// Validate duration fields.
	durations := []struct {
		name  string
		value string
	}{
		{"agent.ping_interval", cfg.Agent.PingInterval},
		{"agent.reconnect_interval", cfg.Agent.ReconnectInterval},
		{"agent.max_reconnect_interval", cfg.Agent.MaxReconnectInterval},
		{"agent.proxy_timeout", cfg.Agent.ProxyTimeout},
	}
	for _, d := range durations {
		if _, err := time.ParseDuration(d.value); err != nil {
			return fmt.Errorf("config: %s: invalid duration %q: %w", d.name, d.value, err)
		}
	}

	return nil
}

// tunnelLabel returns a human-readable label for a tunnel entry in error messages.
func tunnelLabel(index int, name string) string {
	if name != "" {
		return fmt.Sprintf("tunnel[%d] (%s)", index, name)
	}
	return fmt.Sprintf("tunnel[%d]", index)
}
